export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/learn/index',
    'pages/community/index',
    'pages/member/index',
    'pages/learn/ice-robot/index',
    'pages/learn/college-ai/index',
    'pages/learn/path-detail/index',
    'pages/learn/detail',
    'pages/community/detail/index',
    'pages/impact/index',
    'pages/impact/scene-rural',
    'pages/impact/scene-community',
    'pages/impact/scene-museum',
    'pages/care/index',
    'pages/survey/form',
    'pages/story/detail',
    'pages/service/rural',
    'pages/service/community',
    'pages/service/museum',
  ],
  subPackages: [
    {
      root: 'packageTeam',
      pages: ['pages/survey/index'],
    },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#004EA2',
    navigationBarTitleText: '语冰 AI 普惠',
    navigationBarTextStyle: 'white',
    backgroundColor: '#F6F8FA',
  },
  tabBar: {
    color: '#666666',
    selectedColor: '#004EA2',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/icons/home.png',
        selectedIconPath: 'assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/learn/index',
        text: '学习',
        iconPath: 'assets/icons/learn.png',
        selectedIconPath: 'assets/icons/learn-active.png',
      },
      {
        pagePath: 'pages/community/index',
        text: '社区',
        iconPath: 'assets/icons/community.png',
        selectedIconPath: 'assets/icons/community-active.png',
      },
      {
        pagePath: 'pages/member/index',
        text: '我的',
        iconPath: 'assets/icons/member.png',
        selectedIconPath: 'assets/icons/member-active.png',
      },
    ],
  },
})
